User.destroy_all
Organization.destroy_all
Administrator.destroy_all

subway = Organization.create(name: 'Subway')
flatiron = Organization.create(name: 'Flatiron School')

Administrator.create(first_name:'Sheree', last_name:'Shyu', email:'frightened@supernumeraryship.co.uk', organization: flatiron, password: '123')
User.create(first_name:'Hong', last_name:'Litzau', email:'uncowl@reconverse.net', organization: flatiron)
Administrator.create(first_name:'Meggan', last_name:'Gabbin', email:'counterboycott@tortoise.edu', organization: flatiron)
User.create(first_name:'Torri', last_name:'Jedan', email:'transplace@ursoid.co.uk', organization: flatiron)
Administrator.create(first_name:'Charlie', last_name:'Llano', email:'chondritis@aerophone.edu', organization: flatiron)
User.create(first_name:'Mason', last_name:'Noordam', email:'maritorious@whistling.org', organization: flatiron)
Administrator.create(first_name:'Mae', last_name:'Orone', email:'epicotyledonary@lollardize.net', organization: flatiron)
User.create(first_name:'Kerry', last_name:'Dela', email:'benzalaniline@wumble.co.uk', organization: flatiron)
User.create(first_name:'Jacquelin', last_name:'Sampica', email:'clave@uninterestingly.com', organization: flatiron)
Administrator.create(first_name:'Paige', last_name:'Vlach', email:'inciter@tacky.org', organization: flatiron)
User.create(first_name:'Sal', last_name:'Kantis', email:'atropidae@refragableness.com', organization: flatiron)
User.create(first_name:'Elbert', last_name:'Bickerton', email:'staurolitic@ramfeezled.com', organization: flatiron)
User.create(first_name:'Gwenda', last_name:'Langman', email:'emphyteutic@remembrancer.co.uk', organization: flatiron)
User.create(first_name:'Coretta', last_name:'Fishel', email:'shepherd@barthite.com', organization: flatiron)
User.create(first_name:'Senaida', last_name:'Zaza', email:'unjarred@unhearing.edu', organization: flatiron)
User.create(first_name:'Jose', last_name:'Kurpiel', email:'effervescence@disappointer.net', organization: flatiron)
User.create(first_name:'Lovie', last_name:'Schimke', email:'unpulverable@drainless.com', organization: flatiron)
User.create(first_name:'Tameka', last_name:'Dupee', email:'slicer@utch.com', organization: flatiron)
User.create(first_name:'Kathy', last_name:'Zane', email:'ignorer@landlooker.com', organization: flatiron)
User.create(first_name:'Heath', last_name:'Briand', email:'inseparably@answeringly.org', organization: flatiron)
User.create(first_name:'Keira', last_name:'Kasprak', email:'archmugwump@l.org', organization: flatiron)
User.create(first_name:'Shayla', last_name:'Goldstein', email:'horological@borsholder.com', organization: flatiron)
User.create(first_name:'Velma', last_name:'Maire', email:'sulu@housemotherly.com', organization: flatiron)
User.create(first_name:'Angelique', last_name:'Oblinski', email:'permonosulphuric@imonium.edu', organization: flatiron)
User.create(first_name:'Angelina', last_name:'Schurkamp', email:'belittle@mutableness.edu', organization: flatiron)
User.create(first_name:'Vance', last_name:'Laduke', email:'albinotic@parthenocarpical.net', organization: flatiron)
User.create(first_name:'Mandie', last_name:'Malinchalk', email:'representationalist@reclass.com', organization: flatiron)
User.create(first_name:'Ardis', last_name:'Arbeiter', email:'fricandel@grapewise.co.uk', organization: flatiron)
User.create(first_name:'Micki', last_name:'Maaske', email:'phascaceous@vectorial.com', organization: subway)
User.create(first_name:'Levi', last_name:'Vandenberge', email:'wye@astomous.org', organization: subway)
User.create(first_name:'Morris', last_name:'Imbesi', email:'zeuglodont@polygram.org', organization: subway)
User.create(first_name:'Lee', last_name:'Garzia', email:'unwinter@acrologue.edu', organization: subway)
User.create(first_name:'Jin', last_name:'Madarang', email:'unsystemizable@pinchingly.org', organization: subway)
User.create(first_name:'Spring', last_name:'Turkmay', email:'crystallogenesis@hierarchy.co.uk', organization: subway)
User.create(first_name:'Golda', last_name:'Colas', email:'harder@rhizocarpean.org', organization: subway)
User.create(first_name:'Maggie', last_name:'Webre', email:'appropriative@balaniferous.com', organization: subway)
User.create(first_name:'Charlyn', last_name:'Holladay', email:'lockless@rebridge.net', organization: subway)
User.create(first_name:'Hershel', last_name:'Schwieger', email:'inaccessible@sympathicoblast.co.uk', organization: subway)
User.create(first_name:'Elfriede', last_name:'Fleischer', email:'quattie@silicotitanate.edu', organization: subway)
User.create(first_name:'Lucienne', last_name:'Coreas', email:'thalloid@chakazi.com', organization: subway)
User.create(first_name:'Candis', last_name:'Loehner', email:'becloud@chamacea.com', organization: subway)
Administrator.create(first_name:'Linette', last_name:'Shelman', email:'lacrym@magnipotent.org', organization: subway)
User.create(first_name:'Celsa', last_name:'Fahrendorff', email:'incurability@fraternally.edu', organization: subway)
User.create(first_name:'Monnie', last_name:'Iriarte', email:'fernland@amphithyron.net', organization: subway)
Administrator.create(first_name:'Marquita', last_name:'Holec', email:'sheenly@oviform.co.uk', organization: subway)
User.create(first_name:'Brant', last_name:'Boudreaux', email:'aquintocubitalism@quindecagon.co.uk', organization: subway)
User.create(first_name:'Edwardo', last_name:'Middlesworth', email:'uncognized@bilati.com', organization: subway)
Administrator.create(first_name:'Keven', last_name:'Lado', email:'monocystis@hotheaded.co.uk', organization: subway)
User.create(first_name:'Jerry', last_name:'Toxey', email:'portreeve@dorlot.co.uk', organization: subway)
User.create(first_name:'Rick', last_name:'Ostling', email:'discharacter@oppositionist.com', organization: subway)